/*** DTB_USER_CODE_START vvv Add file header below vvv ***/
/*** DTB_USER_CODE_END   ^^^ Add file header above ^^^ ***/

/*
 * File: maillist.h
 * Contains: object data structures and callback declarations
 *
 * This file was generated by dtcodegen, from project maillist
 *
 * Any text may be added between the DTB_USER_CODE_START and
 * DTB_USER_CODE_END comments (even non-C code). Descriptive comments
 * are provided only as an aid.
 *
 *  ** EDIT ONLY WITHIN SECTIONS MARKED WITH DTB_USER_CODE COMMENTS.  **
 *  ** ALL OTHER MODIFICATIONS WILL BE OVERWRITTEN. DO NOT MODIFY OR  **
 *  ** DELETE THE GENERATED COMMENTS!                                 **
 */
#ifndef _MAILLIST_H_
#define _MAILLIST_H_

#include <stdlib.h>
#include <X11/Intrinsic.h>

/*
 * Structure to store values for Application Resources
 */
typedef struct {
    char	*session_file;
    
    /*** DTB_USER_CODE_START vvv Add structure fields below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add structure fields above ^^^ ***/
} DtbAppResourceRec;


extern DtbAppResourceRec	dtb_app_resource_rec;


/**************************************************************************
 *** DTB_USER_CODE_START
 ***
 *** Add types, macros, and externs here
 ***/

/*** DTB_USER_CODE_END
 ***
 *** End of user code section
 ***
 **************************************************************************/


#endif /* _MAILLIST_H_ */
