/*
 * File: module_ui.h
 * Contains: Declarations of module objects, user create procedures,
 *           and callbacks.
 *
 * This file was generated by dtcodegen, from module module
 *
 *    ** DO NOT MODIFY BY HAND - ALL MODIFICATIONS WILL BE LOST **
 */
#ifndef _MODULE_UI_H_
#define _MODULE_UI_H_

#include <stdlib.h>
#include <X11/Intrinsic.h>
#include "dtb_utils.h"

/*
 * User Interface Objects
 */
/*
 * Shared data structures
 */

typedef struct {
    Widget	File_item;
    Widget	Edit_item;
    Widget	Help_item;
} ModuleMenubarItemsRec, *ModuleMenubarItems;
typedef struct
{
    Boolean	initialized;
    
    Widget	mainwindow;	/* object "mainwindow" */
    Widget	mainwindow_mainwin;
    Widget	mainwindow_form;
    
    Widget	menubar;	/* object "menubar" */
    ModuleMenubarItemsRec	menubar_items;
    
    Widget	controlpane;
    
    Widget	list_scrolledwin;	/* object "list" */
    Widget	list;
    
    Widget	button;
} DtbModuleMainwindowInfoRec, *DtbModuleMainwindowInfo;


extern DtbModuleMainwindowInfoRec dtb_module_mainwindow;

/*
 * Structure Clear Procedures: These set the fields to NULL
 */
int dtbModuleMainwindowInfo_clear(DtbModuleMainwindowInfo instance);

/*
 * Structure Initialization Procedures: These create the widgets
 */
int dtb_module_mainwindow_initialize(
    DtbModuleMainwindowInfo	instance,
    Widget	parent
);

/*
 * User Callbacks
 */

/*
 * Connections
 */
#endif /* _MODULE_UI_H_ */
